title: Matchboard
description: Profile & Matches
theme: null

url: "https://jacooob44.github.io"
baseurl: ""   # vigtigt: tom på root-sites

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

markdown: kramdown
