title: Matchboard
description: Profile & Matches
theme: null

# Alle sider bruger vores layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

markdown: kramdown
