title: My Match Site
description: Simple site with Profile & Matches
theme: null   # vigtigt: slå standard tema fra

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
